### PR TITLE
JWKS:vnair - Adding the JWKS functionality.

### PR DESCRIPTION
**Pull request by vibinnair**
Hi @proggeramlug , @calebkleveter ,
 Opening a pull request for the JWKS functionality. 

 This is not the final code, there is some more cleanup required and also caching functionality, needs to be added, in which the obtained JWKS could be persisted for few days.

 I have documented most of my code, but if it is not clear please let me know.

### CODE REVIEW

**Comment by proggeramlug** [comment]
Just glancing over it, it looks pretty awesome! What we will need is some solid tests to guarantee that it works as expected. :)

**Comment by vibinnair** [comment]
Thanks @proggeramlug , will surely add those.

**Comment by vibinnair** [comment]
Hi @proggeramlug , @calebkleveter 
 I have added the unit tests. Please do have a look. Thanks :)

**Comment by vibinnair** [comment]
Hi @calebkleveter , @proggeramlug ,
 Have added the changes.Please have a look and let me know if anything more needs to be done.

**Comment by proggeramlug** [comment]
I've merged it - I will run some tests and then ship it in the next version!

**Pull request merged**
